import os
from datetime import datetime


def generate_report(enumeration_results, output_file):
    """
    Generates a Markdown report based on the enumeration results.

    Args:
        enumeration_results (dict): A dictionary containing enumeration results for each host.
        output_file (str): The path to the output file where the report will be saved.
    """
    with open(output_file, 'w') as file:
        # Write header
        file.write("# Network Enumeration Report\n\n")
        file.write(
            f"**Generated on:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n\n")

        # Write summary
        file.write("## Summary\n\n")
        file.write(f"- **Total Hosts:** {len(enumeration_results)}\n")
        file.write(f"- **Scan Type:** Masscan + Nmap\n\n")

        # Write detailed host information
        file.write("## Discovered Hosts\n\n")

        for host_ip, result in enumeration_results.items():
            file.write(f"### Host: {host_ip}\n\n")

            # Basic info
            file.write("#### Basic Information\n\n")
            file.write("| Property | Value |\n")
            file.write("|----------|-------|\n")
            file.write(f"| IP Address | {result.get('ip_address', 'N/A')} |\n")
            file.write(f"| Hostname | {result.get('hostname', 'Unknown')} |\n")
            file.write(f"| Domain | {result.get('domain', 'N/A')} |\n")
            file.write(f"| OS Type | {result.get('os_type', 'Unknown')} |\n\n")

            # Services
            file.write("#### Active Services\n\n")
            services = result.get('services', [])
            if services:
                file.write("| Service |\n")
                file.write("|----------|\n")
                for service in services:
                    file.write(f"| {service} |\n")
            else:
                file.write("No services detected.\n")
            file.write("\n")

            # Unverified info
            unverified = result.get('unverified_info', [])
            if unverified:
                file.write("#### Unverified Information\n\n")
                for info in unverified:
                    file.write(f"- {info}\n")
                file.write("\n")

            file.write("---\n\n")

        # Footer
        file.write("## Notes\n\n")
        file.write(
            "This report was generated by VectorProbe Network Enumeration Tool.\n")
        file.write("For more information, see the project documentation.\n")
